###Deployment section is responsible for keeping a set of pods running
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objdetectordemo-deployment
  labels:
    app: objdetectordemo
spec:
  # Specify the number of pods to be running and add labels
  replicas: 1
  selector:
    matchLabels:
      app: objdetectordemo
  template:
    metadata:
      labels:
        app: objdetectordemo
    spec:
      containers:
      - name: objdetectordemo
        image: mkprsnt/objdetectordemo:latest
        ports:
        - containerPort: 8000
      - name: webcam
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
---
###Service is responsible for enabling network access to a set of pods
apiVersion: v1
kind: Service
metadata:
  name: objdetectordemo-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  selector:
    app: objdetectordemo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort


