apiVersion: apps/v1
kind: Deployment
metadata:
  name: objdetectordemo-deployment
  labels:
    app: objdetectordemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objdetectordemo
  template:
    metadata:
      labels:
        app: objdetectordemo
    spec:
      containers:
      - name: objdetectordemo
        image: mkprsnt/objdetectordemo:latest
        ports:
        - containerPort: 8000
      - name: webcam
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
---
apiVersion: v1
kind: Service
metadata:
  name: objdetectordemo-service
spec:
  selector:
    app: objdetectordemo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort


